version: "3.6"
services:
#  api:
#    container_name: device_api
#    image: device_api:latest
#    environment:
#      DB_USER: admin
#      DB_PASS: admin

  postgres:
    container_name: postgres_device
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: device
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d device" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  redis:
    driver: local
