serve_addr: ':8080'

probes:
  liveness: "/alive"
  readiness: "/ready"

timeout: '30s'

database:
  kind: postgres
  host: localhost
  port: 5432
  user_env_key: "DB_USER"
  pass_env_key: "DB_PASS"
  dbname: 'device'
  max_connections: 50
  timeout: 10
